import type { CardCategory } from '@/lib/supabase/types'

export const CategoryColors: Record<CardCategory, string> = {
  OpenAI: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
  Anthropic: 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200',
  Google: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200',
  Meta: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200',
  'Open Source': 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200',
  Research: 'bg-cyan-100 text-cyan-800 dark:bg-cyan-900 dark:text-cyan-200',
  Startups: 'bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-200',
  Tools: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200',
  Policy: 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200',
  Industry: 'bg-slate-100 text-slate-800 dark:bg-slate-900 dark:text-slate-200',
} as const

export const FeedStyles = {
  container: 'relative h-dvh bg-black',
  viewport: 'h-full overflow-hidden',
  slideContainer: 'flex h-full touch-pan-y',
  slide: [
    'relative min-w-0 flex-[0_0_100%] h-full',
    'flex items-center justify-center',
  ].join(' '),
  card: [
    'block w-full h-full',
    'flex flex-col justify-center',
    'bg-black text-white',
    'overflow-hidden',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500',
  ].join(' '),
  cardHeader: 'flex items-center justify-between gap-2 px-4 pt-4 pb-2',
  cardBadge: 'inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium',
  cardTime: 'text-xs text-zinc-400 whitespace-nowrap',
  cardTitleContainer: 'px-4 pb-3',
  cardTitle: 'text-base font-semibold leading-snug text-white',
  cardTeaser: 'px-4 pb-3 text-sm text-zinc-300 leading-relaxed',
  keyPointsList: 'px-4 pb-4 space-y-2',
  keyPointsItem: 'flex gap-2 text-sm text-zinc-200 leading-relaxed',
  keyPointsBullet: 'shrink-0 mt-1.5 h-1.5 w-1.5 rounded-full bg-zinc-500',
  cardSourceRow: [
    'flex items-center gap-1.5 px-4 pb-4',
    'text-xs text-zinc-400',
  ].join(' '),
  cardSourceLabel: 'font-medium',
  cardSourceName: 'underline underline-offset-2',
  emptyState: [
    'flex flex-col items-center justify-center',
    'h-dvh px-4',
    'text-zinc-500 dark:text-zinc-400 text-center',
  ].join(' '),
  emptyText: 'text-lg',
  navButton: [
    'absolute top-1/2 z-10 -translate-y-1/2',
    'hidden sm:flex items-center justify-center',
    'h-10 w-10 rounded-full',
    'bg-white/80 dark:bg-zinc-800/80 backdrop-blur-sm',
    'border border-zinc-200 dark:border-zinc-700',
    'text-zinc-700 dark:text-zinc-300',
    'shadow-md',
    'hover:bg-white dark:hover:bg-zinc-800',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500',
    'disabled:opacity-30 disabled:cursor-not-allowed',
  ].join(' '),
  navButtonPrev: 'left-0 -translate-x-1/2',
  navButtonNext: 'right-0 translate-x-1/2',
} as const
